Update model.py
to avoid zero only columns and to prevent
ValueError: Cannot feed value of shape (298, 6) for Tensor 'Placeholder_1:0', which has shape '(?, 4)'